### ISSUE TITLE
反叛技能--强制放逐问题??

### ISSUE THREAD

**Issue by idamonli** [idamonli/RO16TH#7]
![0 (5)](https://user-images.githubusercontent.com/13962741/66011354-61c60a80-e4f5-11e9-9ca9-2e7ab287a2a3.png)
反叛这个技能是群体的，游戏中效果单体。。。另外根源破坏应该是散弹专属技能，但是其他武器也能使用。

**Comment by daxuekuo** [comment]
这个删除了吧，你已经修复了
